from __future__ import annotations
import json
import os
import re
from typing import Dict, List, Optional

from hyprconf2lua.ast import *
from hyprconf2lua.mappings import *


KNOWN_SECTIONS = {
    "general", "decoration", "input", "animations", "gestures",
    "misc", "binds", "cursor", "debug", "dwindle", "master",
    "group", "render", "xwayland", "opengl", "ecosystem",
    "experimental", "layout", "scrolling", "quirks", "blur",
    "shadow", "touchpad", "tablet", "windowing", "startup",
    "autostart", "window", "monitor", "workspace", "layer",
}

MULTI_VALUE_EFFECT_KEYS = {"move", "size", "opacity", "alpha"}


class Codegen:
    def __init__(self):
        self.lines: List[str] = []
        self.indent_level = 0
        self.variables: Dict[str, str] = {}
        self.has_exec = False
        self.has_animation = False
        self.has_bezier = False
        self.has_bind = False
        self.main_mod_var: Optional[str] = None
        self.pending_execs: List[str] = []
        self.pending_exec_ones: List[str] = []
        self.pending_exec_shutdowns: List[str] = []
        self.flag_count = 0
        self.translated_count = 0
        self.passthrough_count = 0

    def indent(self):
        self.indent_level += 1

    def dedent(self):
        self.indent_level = max(0, self.indent_level - 1)

    def emit(self, line: str = ""):
        if line:
            self.lines.append("    " * self.indent_level + line)
        else:
            self.lines.append("")

    def emit_block(self, lines: List[str]):
        for line in lines:
            self.emit(line)

    def generate(self, config: ConfigFile) -> str:
        self.lines = []
        self.emit("-- Generated by hyprconf2lua v1.4.0")
        self.emit("-- https://github.com/Prateek-squadron/hyprconf2lua")
        self.emit("-- Manual review may be needed for complex directives")
        self.emit("")
        self.emit('---@module \'hl\'')
        self.emit("")

        for stmt in config.body:
            self.visit(stmt)
            self.emit()

        self.emit_pending_execs()
        self.finalize_vars()

        return "\n".join(self.lines)

    def visit(self, stmt: BlockStmt):
        if isinstance(stmt, Comment):
            self.emit("--" + stmt.text[1:])
        elif isinstance(stmt, VariableDef):
            self.visit_variable(stmt)
        elif isinstance(stmt, Directive):
            self.visit_directive(stmt)
        elif isinstance(stmt, Section):
            self.visit_section(stmt)
        elif isinstance(stmt, BindDirective):
            self.visit_bind(stmt)
        elif isinstance(stmt, MonitorDirective):
            self.visit_monitor(stmt)
        elif isinstance(stmt, WindowRule):
            self.visit_windowrule(stmt)
        elif isinstance(stmt, WindowRuleBlock):
            self.visit_windowrule_block(stmt)
        elif isinstance(stmt, ExecDirective):
            self.visit_exec(stmt)
        elif isinstance(stmt, AnimationDirective):
            self.visit_animation(stmt)
        elif isinstance(stmt, BezierDirective):
            self.visit_bezier(stmt)
        elif isinstance(stmt, EnvDirective):
            self.visit_env(stmt)
        elif isinstance(stmt, SourceDirective):
            self.visit_source(stmt)
        elif isinstance(stmt, DeviceSection):
            self.visit_device(stmt)
        elif isinstance(stmt, GestureDirective):
            self.visit_gesture(stmt)
        elif isinstance(stmt, WorkspaceDirective):
            self.visit_workspace(stmt)
        elif isinstance(stmt, SubmapDef):
            self.visit_submap(stmt)
        elif isinstance(stmt, LayerRuleDirective):
            self.visit_layerrule(stmt)
        elif isinstance(stmt, LayerRuleBlock):
            self.visit_layerrule_block(stmt)
        else:
            self.flag_count += 1
            self.emit(f"-- TODO: manual review (unknown statement type: {type(stmt).__name__})")

    def resolve_val(self, val: str) -> str:
        def _repl(m: re.Match) -> str:
            var_name = m.group(1)
            if var_name in self.variables:
                return self.variables[var_name]
            return "local_var_" + var_name
        return re.sub(r'\$(\w+)', _repl, val)

    def resolve_val_with_env(self, val: str) -> str:
        def _repl(m: re.Match) -> str:
            var_name = m.group(1)
            if var_name in self.variables:
                return self.variables[var_name]
            if var_name in os.environ:
                return f'os.getenv("{var_name}")'
            return "local_var_" + var_name
        return re.sub(r'\$(\w+)', _repl, val)

    def resolve_val_exec(self, val: str) -> str:
        def _repl(m: re.Match) -> str:
            var_name = m.group(1)
            if var_name in self.variables:
                return self.variables[var_name]
            if var_name in os.environ:
                return f'os.getenv("{var_name}")'
            return m.group(0)
        return re.sub(r'\$(\w+)', _repl, val)

    def _build_concat_expr(self, val: str) -> str:
        parts = re.split(r'(os\.getenv\([^)]+\))', val)
        expr_parts = []
        for part in parts:
            if part.startswith("os.getenv("):
                expr_parts.append(part)
            elif part:
                expr_parts.append(self.quote(part))
        if not expr_parts:
            return '""'
        return " .. ".join(expr_parts)

    def needs_quotes(self, val: str) -> bool:
        if not val:
            return True
        if val.startswith('"') and val.endswith('"'):
            return False
        if re.match(r'^-?\d+(\.\d+)?$', val):
            return False
        if val in ("true", "false", "nil"):
            return False
        if val in self.variables or val in ("mainMod", "terminal", "fileManager", "menu"):
            return False
        if re.match(r'^[a-zA-Z_][a-zA-Z0-9_]*$', val) and val in self.variables:
            return False
        return True

    def quote(self, val: str) -> str:
        if self.needs_quotes(val):
            escaped = val.replace("\\", "\\\\").replace('"', '\\"')
            return f'"{escaped}"'
        return val

    @staticmethod
    def _normalize_key(key: str) -> str:
        return key.replace("-", "_")

    def to_lua_val(self, val: str):
        val = val.strip()
        if val.endswith(";"):
            val = val[:-1].strip()
        val = self.resolve_val_with_env(val)
        if val.startswith("local_var_"):
            return val[len("local_var_"):]
        if "os.getenv(" in val:
            return self._build_concat_expr(val)
        if val.lower() in ("true", "on", "yes"):
            return "true"
        if val.lower() in ("false", "off", "no"):
            return "false"
        try:
            int(val)
            return val
        except ValueError:
            pass
        try:
            float(val)
            return val
        except ValueError:
            pass
        return self.quote(val)

    def visit_variable(self, stmt: VariableDef):
        val = self.resolve_val_with_env(stmt.value)
        self.variables[stmt.name] = val
        self.translated_count += 1
        if stmt.name.upper() == "MAINMOD" or stmt.name == "mainMod":
            self.main_mod_var = stmt.name
            self.emit(f'local {stmt.name} = "{val}"')
        else:
            if self.needs_quotes(val):
                self.emit(f'local {stmt.name} = {self.quote(val)}')
            else:
                self.emit(f'local {stmt.name} = {val}')

    def finalize_vars(self):
        if self.main_mod_var is None:
            for name, val in self.variables.items():
                if val == "SUPER" or val == "ALT" or val == "CTRL" or val == "SHIFT":
                    self.main_mod_var = name
                    break

    def _exec_lua_expr(self, cmd: str) -> str:
        resolved = self.resolve_val_exec(cmd)
        if resolved.startswith("$") and resolved[1:] in self.variables:
            return resolved[1:]
        if "os.getenv(" in resolved:
            return self._build_concat_expr(resolved)
        return self.quote(resolved)

    def emit_pending_execs(self):
        if self.pending_exec_ones:
            self.emit("-- Autostart")
            self.emit('hl.on("hyprland.start", function()')
            self.indent()
            for cmd in self.pending_exec_ones:
                self.emit(f"hl.exec_cmd({self._exec_lua_expr(cmd)})")
            self.dedent()
            self.emit("end)")
            self.emit("")

        if self.pending_execs:
            self.emit("-- Exec (run every reload)")
            self.emit('hl.on("config.reloaded", function()')
            self.indent()
            for cmd in self.pending_execs:
                self.emit(f"hl.exec_cmd({self._exec_lua_expr(cmd)})")
            self.dedent()
            self.emit("end)")
            self.emit("")

        if self.pending_exec_shutdowns:
            self.emit("-- Shutdown")
            self.emit('hl.on("hyprland.shutdown", function()')
            self.indent()
            for cmd in self.pending_exec_shutdowns:
                self.emit(f"hl.exec_cmd({self._exec_lua_expr(cmd)})")
            self.dedent()
            self.emit("end)")
            self.emit("")

    def _is_gradient(self, val: str) -> bool:
        parts = val.strip().split()
        if len(parts) < 3:
            return False
        angle = parts[-1]
        if not angle.endswith("deg"):
            return False
        try:
            float(angle[:-3])
        except ValueError:
            return False
        return True

    def _format_gradient(self, val: str) -> str:
        parts = val.strip().split()
        angle = parts[-1][:-3]
        colors = [self.to_lua_val(p) for p in parts[:-1]]
        return f"{{ colors = {{ {', '.join(colors)} }}, angle = {angle} }}"

    def _emit_directive(self, key: str, values: List[str]):
        if not values or all(not v.strip() for v in values):
            return
        key = self._normalize_key(key)
        if len(values) > 1 and key == "enabled":
            values = values[:1]
        if ":" in key:
            parts = [self._normalize_key(p) for p in key.split(":")]
            inner = f"{parts[-1]} = {{ {', '.join(self.to_lua_val(v) for v in values)} }}"
            if len(values) == 1 and self._is_gradient(values[0]):
                inner = f"{parts[-1]} = {self._format_gradient(values[0])}"
            elif len(values) == 1:
                inner = f"{parts[-1]} = {self.to_lua_val(values[0])}"
            for p in reversed(parts[:-1]):
                inner = f"{p} = {{ {inner} }}"
            self.translated_count += 1
            self.emit(f"{inner},")
            return
        if len(values) == 1 and self._is_gradient(values[0]):
            self.translated_count += 1
            self.emit(f"{key} = {self._format_gradient(values[0])},")
        elif len(values) == 1:
            self.translated_count += 1
            val = self.to_lua_val(values[0])
            self.emit(f"{key} = {val},")
        else:
            self.translated_count += 1
            if key == "kb_options":
                val_str = ",".join(values)
                self.emit(f"{key} = {self.quote(val_str)},")
            else:
                vals = [self.to_lua_val(v) for v in values]
                self.emit(f"{key} = {{ {', '.join(vals)} }},")

    def _group_section_body(self, directives: List[BlockStmt]) -> List[BlockStmt]:
        grouped: List[BlockStmt] = []
        dot_groups = {}
        for d in directives:
            if isinstance(d, Directive) and "." in d.key:
                prefix, suffix = d.key.split(".", 1)
                if prefix not in dot_groups:
                    dot_groups[prefix] = []
                dot_groups[prefix].append(Directive(suffix, d.value, d.line, d.col))
            else:
                grouped.append(d)
        for prefix, subs in dot_groups.items():
            grouped.append(Section(prefix, subs, 0))
        return grouped

    def emit_section_config(self, section_name: str, directives: List[BlockStmt]):
        if not directives:
            return

        deferred: List[BlockStmt] = []

        self.emit(f"hl.config({{")
        self.indent()
        self.emit(f"{section_name} = {{")
        self.indent()

        for d in self._group_section_body(directives):
            if isinstance(d, Comment):
                self.emit(f"--{d.text[1:]}")
            elif isinstance(d, Section):
                sub_name = d.name
                self.emit(f"{sub_name} = {{")
                self.indent()
                for sd in d.body:
                    if isinstance(sd, Comment):
                        self.emit(f"--{sd.text[1:]}")
                    elif isinstance(sd, Directive):
                        self._emit_directive(sd.key, sd.value)
                    elif isinstance(sd, Section):
                        self.passthrough_count += 1
                        self.emit(f"-- Nested subsection {sd.name}:")
                        for ssd in sd.body:
                            if isinstance(ssd, Directive) and ssd.value and ssd.value[0].strip():
                                k = self._normalize_key(ssd.key)
                                vv = self.to_lua_val(ssd.value[0]) if ssd.value else "true"
                                self.emit(f"{k} = {vv},")
                    elif isinstance(sd, (AnimationDirective, BezierDirective, GestureDirective)):
                        deferred.append(sd)
                self.dedent()
                self.emit("},")
            elif isinstance(d, Directive):
                self._emit_directive(d.key, d.value)
            elif isinstance(d, (AnimationDirective, BezierDirective, GestureDirective)):
                deferred.append(d)

        self.dedent()
        self.emit("},")
        self.dedent()
        self.emit("})")

        for node in deferred:
            self.visit(node)

    def flush_subsection(self, name: str, directives: List[Directive]):
        if not directives:
            return
        self.emit(f"{name} = {{")
        self.indent()
        for d in directives:
            key = self._normalize_key(d.key)
            if not d.value or not d.value[0].strip():
                continue
            if len(d.value) == 1:
                val = self.to_lua_val(d.value[0])
                self.emit(f"{key} = {val},")
            else:
                if key == "kb_options":
                    self.emit(f"{key} = {self.quote(','.join(d.value))},")
                else:
                    vals = [self.to_lua_val(v) for v in d.value]
                    self.emit(f"{key} = {{ {', '.join(vals)} }},")
        self.dedent()
        self.emit("},")

    def visit_section(self, stmt: Section):
        if stmt.name == "plugin":
            self.translated_count += 1
            has_plugins = False
            for child in stmt.body:
                if isinstance(child, Section):
                    has_plugins = True
                    plugin_name = child.name
                    self.emit(f"hl.plugin({self.quote(plugin_name)}, function()")
                    self.indent()
                    for sd in child.body:
                        if isinstance(sd, Comment):
                            self.emit(f"--{sd.text[1:]}")
                        elif isinstance(sd, Directive):
                            k = sd.key
                            if len(sd.value) == 1:
                                v = self.to_lua_val(sd.value[0])
                                self.emit(f"{k} = {v},")
                            else:
                                if k == "kb_options":
                                    self.emit(f"{k} = {self.quote(','.join(sd.value))},")
                                else:
                                    vals = [self.to_lua_val(v) for v in sd.value]
                                    self.emit(f"{k} = {{ {', '.join(vals)} }},")
                    self.dedent()
                    self.emit("end)")
                elif isinstance(child, Directive):
                    has_plugins = True
                    name = child.key
                    vals = ", ".join(self.quote(self.resolve_val(v)) for v in child.value)
                    self.emit(f"hl.plugin({self.quote(name)}, {{{vals}}})")
            if not has_plugins:
                self.emit("-- TODO: manual review (plugin config)")
            return
        if stmt.name == "device":
            name = ""
            body = []
            for child in stmt.body:
                if isinstance(child, Directive) and child.key == "name":
                    name = child.value[0] if child.value else ""
                else:
                    body.append(child)
            return self.visit(DeviceSection(name, body, stmt.line))
        if stmt.name in KNOWN_SECTIONS:
            self.emit_section_config(stmt.name, stmt.body)
        else:
            self.translated_count += 1
            deferred: List[BlockStmt] = []
            self.emit(f"hl.config({{")
            self.indent()
            self.emit(f"{stmt.name} = {{")
            self.indent()
            for child in self._group_section_body(stmt.body):
                if isinstance(child, Comment):
                    self.emit(f"--{child.text[1:]}")
                elif isinstance(child, Directive):
                    self._emit_directive(child.key, child.value)
                elif isinstance(child, (AnimationDirective, BezierDirective, GestureDirective)):
                    deferred.append(child)
            self.dedent()
            self.emit("},")
            self.dedent()
            self.emit("})")
            for node in deferred:
                self.visit(node)
            self.emit(f"-- NOTE: Section '{stmt.name}' may be a plugin or custom section; verify the output")

    def visit_directive(self, stmt: Directive):
        if stmt.key in ("submap", "submap_reset"):
            return
        if stmt.key == "unbind":
            self.translated_count += 1
            mods_str = stmt.value[0].strip() if stmt.value else ""
            key_str = stmt.value[1].strip() if len(stmt.value) > 1 else ""
            mods = [m.strip() for m in mods_str.replace(",", " ").split()] if mods_str else []
            combo_expr = self.build_unbind_combo(mods, key_str)
            self.emit(f"hl.unbind({combo_expr})")
            return

        self.passthrough_count += 1
        vals = ", ".join(self.quote(self.resolve_val(v)) for v in stmt.value)
        self.emit(f"-- TODO: manual review: {stmt.key} = {vals}")

    def build_unbind_combo(self, mods: List[str], key: str) -> str:
        if not mods:
            return self.quote(key) if key else '""'
        parts = [self.quote(m) for m in mods]
        all_str = " + ".join(p.strip('"') for p in parts)
        return self.quote(all_str) + ' .. " + " .. ' + (self.quote(key) if key else '""')

    def visit_bind(self, stmt: BindDirective):
        self.translated_count += 1
        self.has_bind = True

        combo_expr = self.build_combo_expr(stmt.mods, stmt.key)

        dispatcher = stmt.dispatcher
        params = stmt.params

        if stmt.key.startswith("mouse:") and not params:
            if dispatcher == "movewindow":
                dsp_code = "hl.dsp.window.drag()"
            elif dispatcher == "resizewindow":
                dsp_code = "hl.dsp.window.resize()"
            else:
                dsp_code = self.build_dispatcher(dispatcher, params)
        else:
            dsp_code = self.build_dispatcher(dispatcher, params)
        if dsp_code is None and params:
            first_param = params[0]
            rest = params[1:]
            dsp_code = self.build_dispatcher(first_param, rest)
            if dsp_code is not None:
                dispatcher = first_param
                params = rest

        if dsp_code is None:
            self.flag_count += 1
            self.emit(f'-- TODO: manual review (unknown dispatcher: {stmt.dispatcher})')
            pstr = ", ".join(self.quote(self.resolve_val(p)) for p in stmt.params)
            self.emit(f'-- hl.bind({combo_expr}, hl.dsp.{stmt.dispatcher}({pstr}))')
            return

        opt_parts = []
        if stmt.flags:
            for f in stmt.flags:
                if f in BIND_FLAGS_TO_OPTIONS:
                    opt_key, opt_val = BIND_FLAGS_TO_OPTIONS[f]
                    opt_parts.append(f"{opt_key} = {opt_val}")

        if opt_parts:
            opts = ", { " + ", ".join(opt_parts) + " }"
        else:
            opts = ""

        self.emit(f"hl.bind({combo_expr}, {dsp_code}{opts})")

    def build_combo_expr(self, mods: List[str], key: str) -> str:
        parts = []

        is_key_var = key.startswith("$")
        key_resolved = self.resolve_val(key) if is_key_var else None
        key_str = key_resolved if is_key_var else self.quote(key)

        for m in mods:
            is_var = m.startswith("$")
            if is_var:
                var_name = m[1:]
                if var_name in self.variables:
                    parts.append(var_name)
                else:
                    parts.append("local_var_" + var_name)
            else:
                parts.append(self.quote(m))

        if not parts:
            return key_str

        has_var = any(not p.startswith('"') for p in parts)

        if not has_var and not is_key_var:
            all_str = " + ".join(p.strip('"') for p in parts)
            return self.quote(all_str + " + " + key_str.strip('"'))

        if not has_var:
            all_str = " + ".join(p.strip('"') for p in parts)
            return self.quote(all_str) + ' .. " + " .. ' + key_str

        segments = []
        current_str = None
        for p in parts:
            if p.startswith('"'):
                lit = p.strip('"')
                if current_str is None:
                    current_str = lit
                else:
                    current_str += " + " + lit
            else:
                if current_str is not None:
                    segments.append(self.quote(current_str))
                    current_str = None
                segments.append(p)
        if current_str is not None:
            segments.append(self.quote(current_str))

        separator = ' .. " + " .. '
        result = separator.join(segments) + separator + key_str
        return result

    def build_dispatcher(self, dispatcher: str, params: List[str]) -> Optional[str]:
        if dispatcher in DISPATCHER_MAP:
            func, needs_args = DISPATCHER_MAP[dispatcher]

            if dispatcher == "movetoworkspace":
                args = self.build_dispatcher_args(params, needs_args, func)
                return f'{func}({args})'

            if dispatcher == "movetoworkspacesilent":
                args = self.build_dispatcher_args(params, needs_args, func)
                # Combine workspace dict with follow flag into single dict
                if args and args.endswith("}"):
                    args = args.rstrip("}") + ", follow = false}"
                return f'{func}({args})'

            if dispatcher == "movefocus":
                dir_map = {"l": "left", "r": "right", "u": "up", "d": "down"}
                if params and params[0] in dir_map:
                    return f'{func}({{ direction = "{dir_map[params[0]]}" }})'
                return f'{func}({{ direction = {self.quote(params[0]) if params else "nil"} }})'

            if dispatcher == "cyclenext":
                if params and params[0].lower() == "prev":
                    return f'{func}({{ next = false }})'
                return f'{func}()'

            if dispatcher == "pass":
                return f'{func}({{ window = {self.quote(params[0]) if params else "nil"} }})'

            if dispatcher == "resizeactive":
                nums = params[0].split() if params else []
                x = nums[0] if len(nums) > 0 else "0"
                y = nums[1] if len(nums) > 1 else "0"
                return f'{func}({{ x = {x}, y = {y}, relative = true }})'

            if dispatcher == "movecurrentworkspacetomonitor":
                mon = self.quote(params[0]) if params else '"l"'
                return f'{func}({{ monitor = {mon} }})'

            if dispatcher == "movewindow":
                if params and params[0].startswith("into_group:"):
                    return f'{func}({{ into_group = {self.quote(params[0][len("into_group:"):])} }})'
                if params and params[0] == "out_of_group":
                    return f'{func}({{ out_of_group = true }})'
                return f'{func}({self.build_dispatcher_args(params, needs_args, func)})'

            if dispatcher == "swapwindow":
                if params and params[0] in ("l", "r", "u", "d"):
                    dir_map = {"l": "left", "r": "right", "u": "up", "d": "down"}
                    return f'{func}({{ direction = "{dir_map[params[0]]}" }})'
                if params and params[0].startswith("class:"):
                    return f'{func}({{ target = {self.quote(params[0])} }})'
                return self.build_dispatcher_args(params, needs_args, func)

            if dispatcher == "changegroupactive":
                if params and params[0].lower() == "f":
                    return f'{func}()'
                return f'{func}({{ forward = false }})'

            if dispatcher == "movegroupwindow":
                if params and params[0].lower() == "b":
                    return f'{func}({{ forward = false }})'
                return f'{func}({{ forward = true }})'

            if dispatcher == "moveintogroup":
                if params:
                    dir_map = {"l": "left", "r": "right", "u": "up", "d": "down"}
                    d = dir_map.get(params[0], params[0])
                    return f'{func}({{ into_group = "{d}" }})'
                return None

            if dispatcher == "moveoutofgroup":
                return f'{func}({{ out_of_group = true }})'

            if dispatcher == "workspace":
                return self.build_workspace_dispatcher(func, params)

            if dispatcher == "focuswindow":
                return self.build_focus_dispatcher(func, params)

            if dispatcher == "focusurgentorlast":
                return f'{func}({{ urgent_or_last = true }})'

            if dispatcher == "focuscurrentorlast":
                return f'{func}({{ last = true }})'

            if dispatcher == "focusonemonitor":
                return f'{func}({{ on_monitor = true }})'

            if dispatcher in ("exec", "execr"):
                raw = params[0] if params else ""
                resolved = self.resolve_val_exec(raw)
                if "os.getenv(" in resolved:
                    return f'{func}({self._build_concat_expr(resolved)})'
                return f'{func}({self.quote(resolved)})'

            if needs_args and not params:
                return None

            args = self.build_dispatcher_args(params, needs_args, func)
            return f'{func}({args})' if needs_args else f'{func}()'

        if dispatcher == "mouse":
            mouse_actions = {"272": "drag", "273": "resize"}
            if params and params[0] in mouse_actions:
                return f'hl.dsp.window.{mouse_actions[params[0]]}()'
            return None

        return None

    def build_workspace_dispatcher(self, func: str, params: List[str]) -> str:
        if not params:
            return f'{func}({{ workspace = "e+1" }})'
        p = params[0]
        if p.isdigit() or (p.startswith("-") and p[1:].isdigit()):
            return f'{func}({{ workspace = {p} }})'
        if p.startswith("special"):
            if ":" in p:
                return f'{func}({{ workspace = {self.quote(p)} }})'
            return f'{func}({{ workspace = "special" }})'
        if p in ("e+1", "e-1", "m+1", "m-1", "r", "empty", "previous"):
            short_map = {"previous": "previous", "empty": "empty", "r": "r"}
            return f'{func}({{ workspace = {self.quote(short_map.get(p, p))} }})'
        if p.startswith("name:"):
            return f'{func}({{ workspace = {self.quote(p[len("name:"):])} }})'
        return f'{func}({{ workspace = {self.quote(p)} }})'

    def build_focus_dispatcher(self, func: str, params: List[str]) -> str:
        if not params:
            return f'{func}({{ window = "" }})'
        p = params[0]
        if p.startswith("class:"):
            return f'{func}({{ window = {self.quote(p)} }})'
        if p.startswith("title:"):
            return f'{func}({{ window = {self.quote(p)} }})'
        if p.startswith("address:"):
            return f'{func}({{ window = {self.quote(p)} }})'
        return f'{func}({{ window = {self.quote(p)} }})'

    def build_dispatcher_args(self, params: List[str], needs_args: bool,
                               func: Optional[str] = None) -> str:
        if not params:
            return "" if not needs_args else "nil"

        if len(params) == 1:
            p = params[0]
            if func and func == "hl.dsp.window.move":
                dir_map = {"l": "left", "r": "right", "u": "up", "d": "down"}
                if p.startswith("special"):
                    return f'{{ workspace = {self.quote(p)} }}'
                if p.isdigit():
                    return f'{{ workspace = {p} }}'
                if re.match(r'^[+-]\d+$', p):
                    return f'{{ workspace = "{p}" }}'
                if p in dir_map:
                    return f'{{ direction = "{dir_map[p]}" }}'
                return f'{{ direction = {self.quote(p)} }}'
            return self.quote(self.resolve_val(p))

        parts = []
        for p in params:
            parts.append(self.quote(self.resolve_val(p)))
        return ", ".join(parts)

    def visit_monitor(self, stmt: MonitorDirective):
        self.translated_count += 1
        self.emit("hl.monitor({")
        self.indent()
        self.emit(f'output   = {self.quote(stmt.name)},')
        self.emit(f'mode     = {self.quote(stmt.mode)},')
        self.emit(f'position = {self.quote(stmt.position)},')
        self.emit(f'scale    = {self.quote(stmt.scale)},')
        for key, val in stmt.extra.items():
            lua_val = self.to_lua_val(val)
            self.emit(f'{key} = {lua_val},')
        self.dedent()
        self.emit("})")

    def _emit_rule_effect(self, prop: str) -> bool:
        words = prop.strip().replace("=", " ").split()
        if not words:
            return False
        key = words[0].lower()
        rest_words = words[1:]
        if key in WINDOW_RULE_MAP:
            k, v = WINDOW_RULE_MAP[key]
            self.emit(f"{k} = {v},")
            return True
        if key in WINDOW_RULE_PARAM_MAP:
            k, needs_val = WINDOW_RULE_PARAM_MAP[key]
            if needs_val and rest_words:
                if key in MULTI_VALUE_EFFECT_KEYS:
                    lua_parts = ", ".join(self.to_lua_val(w) for w in rest_words)
                    self.emit(f"{k} = {{ {lua_parts} }},")
                elif len(rest_words) == 1:
                    self.emit(f"{k} = {self.to_lua_val(rest_words[0])},")
                else:
                    self.emit(f"{k} = {self.quote(' '.join(rest_words))},")
            else:
                self.emit(f"{k} = true,")
            return True
        return False

    def visit_windowrule(self, stmt: WindowRule):
        self.translated_count += 1
        rule = stmt.rule
        match_params = stmt.match_params

        all_params = [rule.strip()] + [mp.strip() for mp in match_params]
        explicit = [p for p in all_params if p.lower().startswith("match:")]
        others = [p for p in all_params if p and p not in explicit]

        match = {}
        if explicit:
            props = others
            for mp in explicit:
                rest = mp[len("match:"):].strip()
                m = re.match(r'^([a-zA-Z0-9_-]+)(?:\s*=\s*|\s*:\s*|\s+)(.*)$', rest)
                if m:
                    match_key, value = m.group(1), m.group(2).strip()
                else:
                    match_key, value = rest, "true"
                if value.lower() == "true":
                    match[match_key] = "true"
                elif value.lower() == "false":
                    match[match_key] = "false"
                else:
                    match[match_key] = self.quote(value)
        else:
            props = [rule]
            for mp in match_params:
                colon_idx = mp.find(":")
                if colon_idx > 0:
                    prefix = mp[:colon_idx].strip()
                    value = mp[colon_idx + 1:].strip()
                    if value.lower() == "true":
                        match[prefix] = "true"
                    elif value.lower() == "false":
                        match[prefix] = "false"
                    else:
                        match[prefix] = self.quote(value)

            if not match and not stmt.is_v2:
                if match_params:
                    match["class"] = self.quote(match_params[0])

        name_source = props[0] if props else rule
        self.emit("hl.window_rule({")
        self.indent()

        name_str = re.sub(r'[^a-zA-Z0-9_-]', '_', name_source[:20].lower())
        name_str = f"{name_str}_{stmt.line}"
        self.emit(f'name  = "{name_str}",')

        self.emit("match = {")
        self.indent()
        for k, v in match.items():
            self.emit(f"{k} = {v},")
        self.dedent()
        self.emit("},")

        for prop in props:
            if not self._emit_rule_effect(prop):
                self.flag_count += 1
                self.emit(f'-- TODO: review rule: {self.quote(prop)}')

        self.dedent()
        self.emit("})")

    def visit_windowrule_block(self, stmt: WindowRuleBlock):
        self.translated_count += 1
        name_str = stmt.name if stmt.name else re.sub(r'[^a-zA-Z0-9_-]', '_', f'rule_{stmt.line}')

        self.emit("hl.window_rule({")
        self.indent()
        self.emit(f'name  = "{name_str}",')

        if stmt.match:
            self.emit("match = {")
            self.indent()
            for k, v in stmt.match.items():
                self.emit(f"{self._normalize_key(k)} = {self.quote(v)},")
            self.dedent()
            self.emit("},")

        for key, vals in stmt.effects.items():
            key = self._normalize_key(key)
            if not vals or not vals[0].strip():
                continue
            if len(vals) == 1 and key not in MULTI_VALUE_EFFECT_KEYS:
                self.emit(f"{key} = {self.to_lua_val(vals[0].strip())},")
            elif len(vals) == 1:
                parts = vals[0].split()
                if len(parts) == 1:
                    self.emit(f"{key} = {self.to_lua_val(parts[0])},")
                else:
                    lua_parts = [self.to_lua_val(p) for p in parts]
                    self.emit(f"{key} = {{ {', '.join(lua_parts)} }},")
            else:
                lua_vals = [self.to_lua_val(v) for v in vals]
                self.emit(f"{key} = {{ {', '.join(lua_vals)} }},")

        self.dedent()
        self.emit("})")

    def visit_exec(self, stmt: ExecDirective):
        self.translated_count += 1
        resolved = self.resolve_val(stmt.command)
        if stmt.kind in ("exec-once", "execr-once"):
            self.pending_exec_ones.append(stmt.command)
        elif stmt.kind == "exec-shutdown":
            self.pending_exec_shutdowns.append(stmt.command)
        else:
            self.pending_execs.append(stmt.command)

    def visit_animation(self, stmt: AnimationDirective):
        self.translated_count += 1
        name = stmt.name
        style = stmt.style
        speed = stmt.speed
        curve = stmt.curve
        enabled = "true" if stmt.enabled.strip().lower() in ("1", "yes", "on", "true") else "false"

        try:
            float(speed)
            speed_lit = speed
        except ValueError:
            speed_lit = self.quote(speed)

        style_extra = ""
        if style and style != "default":
            style_extra = f', style = {self.quote(style)}'

        if curve:
            if re.match(r'^\d+(\.\d+)?$', curve):
                return self.emit(f"-- TODO: manual review (numeric curve ref in animation: {stmt.name})")

            if curve.startswith("spring"):
                spring_parts = curve.split()
                if len(spring_parts) >= 4:
                    self.passthrough_count += 1
                    self.emit(f'hl.animation({{ leaf = "{name}", enabled = {enabled}, speed = {speed_lit}, spring = {self.quote(curve)}{style_extra} }})')
                else:
                    self.emit(f'hl.animation({{ leaf = "{name}", enabled = {enabled}, speed = {speed_lit}, spring = {self.quote(curve)}{style_extra} }})')
            else:
                self.emit(f'hl.animation({{ leaf = "{name}", enabled = {enabled}, speed = {speed_lit}, bezier = {self.quote(curve)}{style_extra} }})')
        else:
            self.emit(f'hl.animation({{ leaf = "{name}", enabled = {enabled}, speed = {speed_lit}{style_extra} }})')

    def visit_bezier(self, stmt: BezierDirective):
        self.translated_count += 1
        self.emit(f'hl.curve({self.quote(stmt.name)}, {{')
        self.indent()
        self.emit(f'type = "bezier",')
        self.emit(f'points = {{ {{ {stmt.p1x}, {stmt.p1y} }}, {{ {stmt.p2x}, {stmt.p2y} }} }},')
        self.dedent()
        self.emit("})")

    def visit_env(self, stmt: EnvDirective):
        self.translated_count += 1
        resolved_name = self.resolve_val(stmt.name)
        name_q = self.quote(resolved_name)
        val_expr = self.to_lua_val(stmt.value)
        self.emit(f"hl.env({name_q}, {val_expr})")

    @staticmethod
    def _sanitize_ident(s: str) -> str:
        return re.sub(r"[^a-zA-Z0-9_]", "_", s)

    def _source_module_path(self, path: str) -> str:
        p = path.strip()
        for marker in ("/.config/hypr/", "/.config/", "$XDG_CONFIG_HOME/", "$HOME/", "~/"):
            if marker in p:
                p = p.split(marker, 1)[1]
                break
        else:
            p = p.lstrip("/")
        p = p.replace(".conf", "")
        return ".".join(self._sanitize_ident(part) for part in p.split("/") if part)

    def visit_source(self, stmt: SourceDirective):
        self.passthrough_count += 1
        path = stmt.path

        if path.endswith("/*.conf"):
            self.emit(f'-- source = {path}')
            self.emit(f"-- NOTE: glob sources need manual handling")
            self.emit(f"-- Directory contents must be required individually")
            return

        module = self._source_module_path(path)
        local_name = module.split(".")[-1]
        self.emit(f'-- source = {path} -> requires manual conversion')
        self.emit(f'-- local {local_name} = require("{module}")')
        self.emit(f'-- TODO: convert {path} to .lua and use require()')

    def visit_device(self, stmt: DeviceSection):
        self.translated_count += 1
        self.emit(f"hl.device({{")
        self.indent()
        self.emit(f'name = {self.quote(stmt.name)},')
        for d in stmt.body:
            if isinstance(d, Directive) and d.value and d.value[0].strip():
                key = self._normalize_key(d.key)
                val = self.to_lua_val(d.value[0]) if d.value else "true"
                self.emit(f"{key} = {val},")
        self.dedent()
        self.emit("})")

    def visit_gesture(self, stmt: GestureDirective):
        self.translated_count += 1
        props = {}
        for d in stmt.body:
            if isinstance(d, Directive):
                props[d.key] = d.value[0] if d.value else "true"

        self.emit("hl.gesture({")
        self.indent()
        for k, v in props.items():
            lua_v = self.to_lua_val(v)
            lua_k = k.replace("_", " ")
            self.emit(f"[{self.quote(lua_k)}] = {lua_v},")
        self.dedent()
        self.emit("})")

    def visit_submap(self, stmt: SubmapDef):
        self.translated_count += 1
        self.emit(f'hl.define_submap({self.quote(stmt.name)}, function()')
        self.indent()
        for s in stmt.body:
            if isinstance(s, Comment):
                self.emit("--" + s.text[1:])
            elif isinstance(s, BindDirective):
                self.visit_bind(s)
            elif isinstance(s, Directive):
                if s.key == "submap_reset":
                    continue
                self.emit(f'-- submap: {s.key} = {", ".join(s.value)}')
        self.dedent()
        self.emit("end)")
        self.emit("")

    def visit_workspace(self, stmt: WorkspaceDirective):
        self.translated_count += 1
        self.emit("hl.workspace_rule({")
        self.indent()
        self.emit(f'workspace = {self.quote(stmt.name)},')
        for param in stmt.params:
            colon_idx = param.find(":")
            if colon_idx > 0:
                key = param[:colon_idx].strip()
                val = param[colon_idx + 1:].strip()
                lua_key = WORKSPACE_RULE_MAP.get(key, key)
                lua_val = self.to_lua_val(val)
                self.emit(f"{lua_key} = {lua_val},")
            else:
                self.emit(f'-- {param} (unrecognized workspace param)')
        self.dedent()
        self.emit("})")

    def visit_layerrule(self, stmt: LayerRuleDirective):
        self.translated_count += 1
        rule_raw = stmt.rule.strip()
        ns = stmt.namespace.strip()

        if ns.lower().startswith("match:"):
            ns = ns[len("match:"):].strip()
        m = re.match(r'^namespace\s*(?:=|:)?\s*(.+)$', ns, re.IGNORECASE)
        if m:
            ns = m.group(1).strip()

        norm_words = rule_raw.replace("=", " ").split()
        key = norm_words[0].lower() if norm_words else ""
        value = " ".join(norm_words[1:]) if len(norm_words) > 1 else None

        self.emit("hl.layer_rule({")
        self.indent()
        self.emit("match = {")
        self.indent()
        self.emit(f'namespace = {self.quote(ns)},')
        self.dedent()
        self.emit("},")

        applied = False
        if key in LAYER_RULE_MAP:
            k, v = LAYER_RULE_MAP[key]
            if isinstance(v, str) and v in ("true", "false"):
                self.emit(f"{k} = {v},")
            elif value:
                self.emit(f"{k} = {self.to_lua_val(value)},")
            else:
                self.emit(f"{k} = true,")
            applied = True

        if not applied and key:
            self.emit(f"{norm_words[0]} = {self.quote(' '.join(norm_words[1:])) if len(norm_words) > 1 else 'true'},")

        self.dedent()
        self.emit("})")

    def visit_layerrule_block(self, stmt: LayerRuleBlock):
        self.translated_count += 1
        name_str = stmt.name if stmt.name else f'layerrule_{stmt.line}'

        self.emit("hl.layer_rule({")
        self.indent()

        if stmt.match:
            self.emit("match = {")
            self.indent()
            for k, v in stmt.match.items():
                self.emit(f"{self._normalize_key(k)} = {self.quote(v)},")
            self.dedent()
            self.emit("},")

        for key, vals in stmt.effects.items():
            key = self._normalize_key(key)
            if not vals or not vals[0].strip():
                continue
            if len(vals) == 1 and key not in MULTI_VALUE_EFFECT_KEYS:
                self.emit(f"{key} = {self.to_lua_val(vals[0].strip())},")
            elif len(vals) == 1:
                parts = vals[0].split()
                if len(parts) == 1:
                    self.emit(f"{key} = {self.to_lua_val(parts[0])},")
                else:
                    lua_parts = [self.to_lua_val(p) for p in parts]
                    self.emit(f"{key} = {{ {', '.join(lua_parts)} }},")
            else:
                lua_vals = [self.to_lua_val(v) for v in vals]
                self.emit(f"{key} = {{ {', '.join(lua_vals)} }},")

        self.dedent()
        self.emit("})")

    def get_report(self) -> dict:
        return {
            "translated": self.translated_count,
            "passthrough": self.passthrough_count,
            "flagged": self.flag_count,
        }
