DISPATCHER_MAP = {
    "exec":              ("hl.dsp.exec_cmd", True),
    "execr":             ("hl.dsp.exec_raw", True),
    "killactive":        ("hl.dsp.window.close", False),
    "kill":              ("hl.dsp.window.kill", False),
    "exit":              ("hl.dsp.exit", False),
    "fullscreen":        ("hl.dsp.window.fullscreen", False),
    "fullscreenstate":   ("hl.dsp.window.fullscreen_state", True),
    "togglefloating":    ("hl.dsp.window.float", False),
    "setfloating":       ("hl.dsp.window.float", True),
    "pseudo":            ("hl.dsp.window.pseudo", False),
    "togglesplit":       ("hl.dsp.layout", True),
    "layoutmsg":         ("hl.dsp.layout", True),
    "cyclenext":         ("hl.dsp.window.cycle_next", False),
    "focuswindow":       ("hl.dsp.focus", True),
    "focuscurrentorlast":("hl.dsp.focus", True),
    "movefocus":         ("hl.dsp.focus", True),
    "movewindow":        ("hl.dsp.window.move", True),
    "swapwindow":        ("hl.dsp.window.swap", True),
    "swapnext":          ("hl.dsp.window.swap", True),
    "centerwindow":      ("hl.dsp.window.center", False),
    "resizewindow":      ("hl.dsp.window.resize", True),
    "movecursor":        ("hl.dsp.cursor.move", True),
    "pin":               ("hl.dsp.window.pin", False),
    "tag":               ("hl.dsp.window.tag", True),
    "togglegroup":       ("hl.dsp.group.toggle", False),
    "changegroupactive": ("hl.dsp.group.next", False),
    "focusgroupwindow":  ("hl.dsp.group.active", True),
    "movegroupwindow":   ("hl.dsp.group.move_window", True),
    "lockgroups":        ("hl.dsp.group.lock", False),
    "workspace":         ("hl.dsp.focus", True),
    "movetoworkspace":   ("hl.dsp.window.move", True),
    "movetoworkspacesilent": ("hl.dsp.window.move", True),
    "focusmonitor":      ("hl.dsp.focus", True),
    "movetomonitor":     ("hl.dsp.window.move", True),
    "togglespecialworkspace": ("hl.dsp.workspace.toggle_special", True),
    "renameworkspace":   ("hl.dsp.workspace.rename", True),
    "alterzorder":       ("hl.dsp.window.alter_zorder", True),
    "setprop":           ("hl.dsp.window.set_prop", True),
    "swallows":          ("hl.dsp.window.toggle_swallow", False),
    "denywindowfromgroup":("hl.dsp.window.deny_from_group", False),
    "submap":            ("hl.dsp.submap", True),
    "pass":              ("hl.dsp.pass", True),
    "sendshortcut":      ("hl.dsp.send_shortcut", True),
    "dpms":              ("hl.dsp.dpms", True),
    "noop":              ("hl.dsp.no_op", False),
    "event":             ("hl.dsp.event", True),
    "global":            ("hl.dsp.global", True),
    "forceidle":         ("hl.dsp.force_idle", True),
    "moveintogroup":     ("hl.dsp.window.move", True),
    "moveoutofgroup":    ("hl.dsp.window.move", True),
    "focusurgentorlast": ("hl.dsp.focus", True),
    "focusonemonitor":   ("hl.dsp.focus", True),
    "forcekillactive":   ("hl.dsp.window.kill", False),
}

BIND_FLAGS_TO_OPTIONS = {
    "l": ("locked", "true"),
    "r": ("repeating", "true"),
    "n": ("non_consuming", "true"),
    "m": ("mouse", "true"),
    "e": ("empty", "true"),
    "t": ("transparent", "true"),
    "i": ("ignore_mods", "true"),
    "p": ("pass", "true"),
}

WINDOW_RULE_MAP = {
    "float":        ("float", "true"),
    "tile":         ("tile", "true"),
    "pin":          ("pin", "true"),
    "nofocus":      ("no_focus", "true"),
    "noborder":     ("border", "false"),
    "noblur":       ("blur", "false"),
    "noshadow":     ("shadow", "false"),
    "noanim":       ("no_anim", "true"),
    "dimaround":    ("dim_around", "true"),
    "nomaxsize":    ("max_size", "false"),
    "fakefullscreen": ("fake_fullscreen", "true"),
    "noinitialfocus": ("no_initial_focus", "true"),
    "windowdance":  ("window_dance", "true"),
    "nofullscreenrequests": ("suppress_event", "fullscreen"),
    "nomaximizerequest": ("suppress_event", "maximize"),
}

WINDOW_RULE_PARAM_MAP = {
    "opacity":      ("opacity", True),
    "alpha":        ("alpha", True),
    "border_size":  ("border_size", True),
    "rounding":     ("rounding", True),
    "monitor":      ("monitor", True),
    "workspace":    ("workspace", True),
    "move":         ("move", True),
    "size":         ("size", True),
    "minsize":      ("min_size", True),
    "maxsize":      ("max_size", True),
    "idleinhibit":  ("idle_inhibit", True),
    "xray":         ("xray", True),
    "center":       ("center", True),
    "keepaspectratio": ("keep_aspect_ratio", "true"),
    "dimaround":    ("dim_around", "true"),
    "fullscreen":   ("fullscreen", True),
    "maximize":     ("maximize", True),
    "suppressevent": ("suppress_event", True),
    "pseudo":       ("pseudo", "true"),
    "stayfocused":  ("stay_focused", "true"),
    "group":        ("group", True),
    "scroll_touchpad": ("scroll_touchpad", True),
}

WORKSPACE_RULE_MAP = {
    "monitor":      "monitor",
    "default":      "is_default",
    "gapsin":       "gaps_in",
    "gapsout":      "gaps_out",
    "bordersize":   "border_size",
    "rounding":     "rounding",
    "decorate":     "decorate",
    "persistent":   "persistent",
}

LAYER_RULE_MAP = {
    "blur":         ("blur", "true"),
    "ignorealpha":  ("ignore_alpha", True),
    "ignorezero":   ("ignore_alpha", True),
    "noanim":       ("no_anim", "true"),
    "noblur":       ("blur", "false"),
}
