# Canonical XF86 keysym spellings (from X11/XF86keysym.h), keyed by
# lowercased name. hl.bind's key parser expects the exact spelling; many
# real-world configs write these in arbitrary case since the old hyprlang
# parser was lenient about it.
XF86_KEYSYM_MAP = {
    "addfavorite": "AddFavorite",
    "applicationleft": "ApplicationLeft",
    "applicationright": "ApplicationRight",
    "audiocycletrack": "AudioCycleTrack",
    "audioforward": "AudioForward",
    "audiolowervolume": "AudioLowerVolume",
    "audiomedia": "AudioMedia",
    "audiomicmute": "AudioMicMute",
    "audiomute": "AudioMute",
    "audionext": "AudioNext",
    "audiopause": "AudioPause",
    "audioplay": "AudioPlay",
    "audiopreset": "AudioPreset",
    "audioprev": "AudioPrev",
    "audioraisevolume": "AudioRaiseVolume",
    "audiorandomplay": "AudioRandomPlay",
    "audiorecord": "AudioRecord",
    "audiorepeat": "AudioRepeat",
    "audiorewind": "AudioRewind",
    "audiostop": "AudioStop",
    "away": "Away",
    "back": "Back",
    "backforward": "BackForward",
    "battery": "Battery",
    "blue": "Blue",
    "bluetooth": "Bluetooth",
    "book": "Book",
    "brightnessadjust": "BrightnessAdjust",
    "calculater": "Calculater",
    "calculator": "Calculator",
    "calendar": "Calendar",
    "cd": "CD",
    "clear": "Clear",
    "cleargrab": "ClearGrab",
    "close": "Close",
    "community": "Community",
    "contrastadjust": "ContrastAdjust",
    "copy": "Copy",
    "cut": "Cut",
    "cycleangle": "CycleAngle",
    "display": "Display",
    "documents": "Documents",
    "dos": "DOS",
    "eject": "Eject",
    "excel": "Excel",
    "explorer": "Explorer",
    "favorites": "Favorites",
    "finance": "Finance",
    "forward": "Forward",
    "frameback": "FrameBack",
    "frameforward": "FrameForward",
    "fullscreen": "FullScreen",
    "game": "Game",
    "go": "Go",
    "green": "Green",
    "hibernate": "Hibernate",
    "history": "History",
    "homepage": "HomePage",
    "hotlinks": "HotLinks",
    "itouch": "iTouch",
    "kbdbrightnessdown": "KbdBrightnessDown",
    "kbdbrightnessup": "KbdBrightnessUp",
    "kbdlightonoff": "KbdLightOnOff",
    "keyboard": "Keyboard",
    "launch0": "Launch0",
    "launch1": "Launch1",
    "launch2": "Launch2",
    "launch3": "Launch3",
    "launch4": "Launch4",
    "launch5": "Launch5",
    "launch6": "Launch6",
    "launch7": "Launch7",
    "launch8": "Launch8",
    "launch9": "Launch9",
    "launcha": "LaunchA",
    "launchb": "LaunchB",
    "launchc": "LaunchC",
    "launchd": "LaunchD",
    "launche": "LaunchE",
    "launchf": "LaunchF",
    "lightbulb": "LightBulb",
    "loggrabinfo": "LogGrabInfo",
    "logoff": "LogOff",
    "logwindowtree": "LogWindowTree",
    "macrorecordstart": "MacroRecordStart",
    "mail": "Mail",
    "mailforward": "MailForward",
    "market": "Market",
    "mediaselectcd": "MediaSelectCD",
    "meeting": "Meeting",
    "memo": "Memo",
    "menukb": "MenuKB",
    "menupb": "MenuPB",
    "messenger": "Messenger",
    "modelock": "ModeLock",
    "monbrightnesscycle": "MonBrightnessCycle",
    "monbrightnessdown": "MonBrightnessDown",
    "monbrightnessup": "MonBrightnessUp",
    "music": "Music",
    "mycomputer": "MyComputer",
    "mysites": "MySites",
    "new": "New",
    "news": "News",
    "next_vmode": "Next_VMode",
    "officehome": "OfficeHome",
    "open": "Open",
    "openurl": "OpenURL",
    "option": "Option",
    "paste": "Paste",
    "phone": "Phone",
    "pictures": "Pictures",
    "powerdown": "PowerDown",
    "poweroff": "PowerOff",
    "prev_vmode": "Prev_VMode",
    "q": "Q",
    "red": "Red",
    "refresh": "Refresh",
    "reload": "Reload",
    "reply": "Reply",
    "rfkill": "RFKill",
    "rockerdown": "RockerDown",
    "rockerenter": "RockerEnter",
    "rockerup": "RockerUp",
    "rotatewindows": "RotateWindows",
    "rotationkb": "RotationKB",
    "rotationlocktoggle": "RotationLockToggle",
    "rotationpb": "RotationPB",
    "save": "Save",
    "screensaver": "ScreenSaver",
    "scrollclick": "ScrollClick",
    "scrolldown": "ScrollDown",
    "scrollup": "ScrollUp",
    "search": "Search",
    "select": "Select",
    "send": "Send",
    "shop": "Shop",
    "sleep": "Sleep",
    "spell": "Spell",
    "splitscreen": "SplitScreen",
    "standby": "Standby",
    "start": "Start",
    "stop": "Stop",
    "subtitle": "Subtitle",
    "support": "Support",
    "suspend": "Suspend",
    "switch_vt_1": "Switch_VT_1",
    "switch_vt_10": "Switch_VT_10",
    "switch_vt_11": "Switch_VT_11",
    "switch_vt_12": "Switch_VT_12",
    "switch_vt_2": "Switch_VT_2",
    "switch_vt_3": "Switch_VT_3",
    "switch_vt_4": "Switch_VT_4",
    "switch_vt_5": "Switch_VT_5",
    "switch_vt_6": "Switch_VT_6",
    "switch_vt_7": "Switch_VT_7",
    "switch_vt_8": "Switch_VT_8",
    "switch_vt_9": "Switch_VT_9",
    "taskpane": "TaskPane",
    "terminal": "Terminal",
    "time": "Time",
    "todolist": "ToDoList",
    "tools": "Tools",
    "topmenu": "TopMenu",
    "touchpadoff": "TouchpadOff",
    "touchpadon": "TouchpadOn",
    "touchpadtoggle": "TouchpadToggle",
    "travel": "Travel",
    "ungrab": "Ungrab",
    "user1kb": "User1KB",
    "user2kb": "User2KB",
    "userpb": "UserPB",
    "uwb": "UWB",
    "vendorhome": "VendorHome",
    "video": "Video",
    "view": "View",
    "wakeup": "WakeUp",
    "webcam": "WebCam",
    "wheelbutton": "WheelButton",
    "wlan": "WLAN",
    "word": "Word",
    "wwan": "WWAN",
    "www": "WWW",
    "xfer": "Xfer",
    "yellow": "Yellow",
    "zoomin": "ZoomIn",
    "zoomout": "ZoomOut",
}

DISPATCHER_MAP = {
    "exec":              ("hl.dsp.exec_cmd", True),
    "execr":             ("hl.dsp.exec_raw", True),
    "killactive":        ("hl.dsp.window.close", False),
    "kill":              ("hl.dsp.window.kill", False),
    "exit":              ("hl.dsp.exit", False),
    "fullscreen":        ("hl.dsp.window.fullscreen", False),
    "fullscreenstate":   ("hl.dsp.window.fullscreen_state", True),
    "togglefloating":    ("hl.dsp.window.float", False),
    "setfloating":       ("hl.dsp.window.float", True),
    "pseudo":            ("hl.dsp.window.pseudo", False),
    "togglesplit":       ("hl.dsp.layout", True),
    "layoutmsg":         ("hl.dsp.layout", True),
    "cyclenext":         ("hl.dsp.window.cycle_next", False),
    "focuswindow":       ("hl.dsp.focus", True),
    "focuscurrentorlast":("hl.dsp.focus", True),
    "movefocus":         ("hl.dsp.focus", True),
    "movewindow":        ("hl.dsp.window.move", True),
    "swapwindow":        ("hl.dsp.window.swap", True),
    "swapnext":          ("hl.dsp.window.swap", True),
    "centerwindow":      ("hl.dsp.window.center", False),
    "resizewindow":      ("hl.dsp.window.resize", True),
    "movecursor":        ("hl.dsp.cursor.move", True),
    "pin":               ("hl.dsp.window.pin", False),
    "tag":               ("hl.dsp.window.tag", True),
    "togglegroup":       ("hl.dsp.group.toggle", False),
    "changegroupactive": ("hl.dsp.group.next", False),
    "focusgroupwindow":  ("hl.dsp.group.active", True),
    "movegroupwindow":   ("hl.dsp.group.move_window", True),
    "lockgroups":        ("hl.dsp.group.lock", False),
    "workspace":         ("hl.dsp.focus", True),
    "movetoworkspace":   ("hl.dsp.window.move", True),
    "movetoworkspacesilent": ("hl.dsp.window.move", True),
    "focusmonitor":      ("hl.dsp.focus", True),
    "movetomonitor":     ("hl.dsp.window.move", True),
    "togglespecialworkspace": ("hl.dsp.workspace.toggle_special", True),
    "renameworkspace":   ("hl.dsp.workspace.rename", True),
    "alterzorder":       ("hl.dsp.window.alter_zorder", True),
    "setprop":           ("hl.dsp.window.set_prop", True),
    "swallows":          ("hl.dsp.window.toggle_swallow", False),
    "denywindowfromgroup":("hl.dsp.window.deny_from_group", False),
    "submap":            ("hl.dsp.submap", True),
    "pass":              ("hl.dsp.pass", True),
    "sendshortcut":      ("hl.dsp.send_shortcut", True),
    "dpms":              ("hl.dsp.dpms", True),
    "noop":              ("hl.dsp.no_op", False),
    "event":             ("hl.dsp.event", True),
    "global":            ("hl.dsp.global", True),
    "forceidle":         ("hl.dsp.force_idle", True),
    "moveintogroup":     ("hl.dsp.window.move", True),
    "moveoutofgroup":    ("hl.dsp.window.move", True),
    "focusurgentorlast": ("hl.dsp.focus", True),
    "focusonemonitor":   ("hl.dsp.focus", True),
    "forcekillactive":   ("hl.dsp.window.kill", False),
    "bringactivetotop":  ("hl.dsp.window.bring_to_top", False),
    "resizeactive":      ("hl.dsp.window.resize", True),
    "movecurrentworkspacetomonitor": ("hl.dsp.workspace.move", True),
}

BIND_FLAGS_TO_OPTIONS = {
    "l": ("locked", "true"),
    "r": ("repeating", "true"),
    "n": ("non_consuming", "true"),
    "m": ("mouse", "true"),
    "e": ("empty", "true"),
    "t": ("transparent", "true"),
    "i": ("ignore_mods", "true"),
    "p": ("pass", "true"),
}

WINDOW_RULE_MAP = {
    "float":        ("float", "true"),
    "tile":         ("tile", "true"),
    "pin":          ("pin", "true"),
    "nofocus":      ("no_focus", "true"),
    "noborder":     ("border", "false"),
    "noblur":       ("blur", "false"),
    "noshadow":     ("shadow", "false"),
    "noanim":       ("no_anim", "true"),
    "dimaround":    ("dim_around", "true"),
    "nomaxsize":    ("max_size", "false"),
    "fakefullscreen": ("fake_fullscreen", "true"),
    "noinitialfocus": ("no_initial_focus", "true"),
    "windowdance":  ("window_dance", "true"),
    "nofullscreenrequests": ("suppress_event", "fullscreen"),
    "nomaximizerequest": ("suppress_event", "maximize"),
}

WINDOW_RULE_PARAM_MAP = {
    "opacity":      ("opacity", True),
    "alpha":        ("alpha", True),
    "border_size":  ("border_size", True),
    "rounding":     ("rounding", True),
    "monitor":      ("monitor", True),
    "workspace":    ("workspace", True),
    "move":         ("move", True),
    "size":         ("size", True),
    "minsize":      ("min_size", True),
    "maxsize":      ("max_size", True),
    "idleinhibit":  ("idle_inhibit", True),
    "xray":         ("xray", True),
    "center":       ("center", True),
    "keepaspectratio": ("keep_aspect_ratio", "true"),
    "dimaround":    ("dim_around", "true"),
    "fullscreen":   ("fullscreen", True),
    "maximize":     ("maximize", True),
    "suppressevent": ("suppress_event", True),
    "pseudo":       ("pseudo", "true"),
    "stayfocused":  ("stay_focused", "true"),
    "tag":          ("tag", True),
    "group":        ("group", True),
    "scroll_touchpad": ("scroll_touchpad", True),
}

WORKSPACE_RULE_MAP = {
    "monitor":      "monitor",
    "default":      "is_default",
    "gapsin":       "gaps_in",
    "gapsout":      "gaps_out",
    "bordersize":   "border_size",
    "rounding":     "rounding",
    "decorate":     "decorate",
    "persistent":   "persistent",
}

LAYER_RULE_MAP = {
    "blur":         ("blur", "true"),
    "ignorealpha":  ("ignore_alpha", "true"),
    "ignorezero":   ("ignore_alpha", "true"),
    "noanim":       ("no_anim", "true"),
    "noblur":       ("blur", "false"),
}
